<template>
  <div class="modal-overlay" @click.self="$emit('close')">
    <div class="modal-box">
      <div class="modal-header">
        <div>
          <div class="modal-title">Generate Daily Summary</div>
          <div class="modal-sub">Confirm the daily POS manager summary details before printing the report.</div>
        </div>
        <div style="display:flex;gap:8px;">
          <button class="btn-outline" @click="$emit('close')">Close</button>
          <button class="btn-primary" @click="printSummary">Print Copy</button>
        </div>
      </div>

      <!-- Report Snapshot -->
      <div class="snapshot-bar">
        <div><div class="snap-label">Report Date</div><div class="snap-val">15 Apr 2026</div></div>
        <div><div class="snap-label">Generated By</div><div class="snap-val">Manager On Duty</div></div>
        <div><div class="snap-label">Scope</div><div class="snap-val">All POS Outlets</div></div>
        <div><div class="snap-label">Format</div><div class="snap-val">Printable Summary</div></div>
      </div>

      <div style="display:grid;grid-template-columns:1fr 280px;gap:20px;margin-top:20px;">
        <!-- Printable Preview -->
        <div>
          <div class="inner-section-title">Printable Preview</div>
          <div class="print-preview">
            <div class="print-title">POS Manager Daily Summary</div>
            <div class="print-date">Date: 15 Apr 2026 • Generated: 08:10 PM</div>
            <div class="print-divider"></div>
            <div class="print-row"><span>Gross Sales</span><span>₦3.86M</span></div>
            <div class="print-row"><span>Net Collections</span><span>₦3.52M</span></div>
            <div class="print-row"><span>Invoices Processed</span><span>98</span></div>
            <div class="print-row"><span>Open Drafts</span><span style="color:#d97706;font-weight:600;">7</span></div>
            <div class="print-row"><span>Open Tables</span><span style="color:#d97706;font-weight:600;">14</span></div>
            <div class="print-row"><span>Shift Differences</span><span style="color:#dc2626;font-weight:600;">₦41,300</span></div>
            <div class="print-divider"></div>
            <div class="print-section-title">Outlet Performance</div>
            <div class="print-row"><span>Main Restaurant</span><span>₦1.82M</span></div>
            <div class="print-row"><span>Bar Lounge</span><span>₦1.06M</span></div>
            <div class="print-row"><span>Retail Corner</span><span>₦980K</span></div>
            <div class="print-divider"></div>
            <div class="print-section-title">Key Notes</div>
            <div class="print-notes">
              <div>• 4 difference cases reviewed, 1 still pending manager follow-up.</div>
              <div>• 2 room-posted invoices awaiting final folio confirmation.</div>
              <div>• Evening coverage at retail corner requires reinforcement tomorrow.</div>
            </div>
          </div>
        </div>

        <!-- Confirmation Settings -->
        <div>
          <div class="inner-section-title">Confirmation Settings</div>
          <div class="setting-group">
            <div class="setting-label">Summary Scope</div>
            <select class="filter-select-full">
              <option>All POS Outlets</option>
              <option>Main Restaurant Only</option>
              <option>Bar Lounge Only</option>
            </select>
          </div>
          <div class="setting-group">
            <div class="setting-label">Include Sections</div>
            <div class="checkbox-group">
              <label v-for="s in sections" :key="s.key" class="checkbox-item">
                <input type="checkbox" v-model="s.checked" />
                {{ s.label }}
              </label>
            </div>
          </div>
          <div class="setting-group">
            <div class="setting-label">Print Layout</div>
            <div class="layout-option active">A4 Portrait • Printable</div>
          </div>
          <div class="setting-group">
            <div class="setting-label">Manager Note</div>
            <textarea class="note-area" placeholder="Optional note to appear at the bottom of the printed summary..."></textarea>
          </div>
          <div class="setting-group">
            <div class="setting-label">Output Action</div>
            <div style="font-size:12px;color:#64748b;background:#f8fafc;border-radius:6px;padding:9px 10px;">Use the top-right Print Copy button to print this summary.</div>
          </div>
        </div>
      </div>

      <!-- Toast -->
      <div class="toast-bar">
        <span class="toast-dot">✓</span> Printable POS manager daily summary is ready.
      </div>
    </div>
  </div>
</template>

<script setup>
import { reactive } from 'vue'

defineEmits(['close'])

const sections = reactive([
  { key: 'sales', label: 'Sales summary', checked: true },
  { key: 'outlet', label: 'Outlet performance', checked: true },
  { key: 'drafts', label: 'Drafts and open tables', checked: true },
  { key: 'diff', label: 'Difference review summary', checked: true },
])

function printSummary() { window.print() }
</script>

<style scoped>
.modal-overlay { position: fixed; inset: 0; background: rgba(15,23,42,0.5); display: flex; align-items: center; justify-content: center; z-index: 1000; padding: 20px; }
.modal-box { background: white; border-radius: 12px; padding: 24px; max-width: 860px; width: 100%; max-height: 92vh; overflow-y: auto; box-shadow: 0 20px 60px rgba(0,0,0,0.2); font-family: 'DM Sans', sans-serif; }
.modal-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 18px; gap: 16px; }
.modal-title { font-size: 20px; font-weight: 700; color: #0f172a; }
.modal-sub { font-size: 12px; color: #64748b; margin-top: 3px; }
.snapshot-bar { display: grid; grid-template-columns: repeat(4,1fr); gap: 12px; background: #f8fafc; border-radius: 8px; padding: 14px 16px; }
.snap-label { font-size: 11px; color: #64748b; margin-bottom: 2px; }
.snap-val { font-size: 14px; font-weight: 600; color: #0f172a; }
.inner-section-title { font-size: 14px; font-weight: 600; color: #0f172a; margin-bottom: 12px; }
.print-preview { border: 1px solid #e2e8f0; border-radius: 8px; padding: 18px 20px; background: white; }
.print-title { font-size: 16px; font-weight: 700; color: #0f172a; }
.print-date { font-size: 12px; color: #64748b; margin-top: 2px; margin-bottom: 10px; }
.print-divider { height: 1px; background: #e2e8f0; margin: 10px 0; }
.print-row { display: flex; justify-content: space-between; font-size: 13px; padding: 4px 0; color: #374151; }
.print-section-title { font-size: 13px; font-weight: 600; color: #0f172a; margin-bottom: 4px; }
.print-notes { font-size: 12px; color: #64748b; line-height: 2; }
.setting-group { margin-bottom: 16px; }
.setting-label { font-size: 12px; font-weight: 600; color: #374151; margin-bottom: 6px; }
.filter-select-full { width: 100%; border: 1px solid #e2e8f0; border-radius: 7px; padding: 8px 12px; font-size: 13px; background: white; cursor: pointer; outline: none; }
.checkbox-group { background: #f8fafc; border-radius: 7px; padding: 10px 12px; display: flex; flex-direction: column; gap: 8px; }
.checkbox-item { display: flex; align-items: center; gap: 8px; font-size: 13px; color: #374151; cursor: pointer; }
.checkbox-item input { accent-color: #1d4ed8; width: 14px; height: 14px; }
.layout-option { border: 1.5px solid #3b82f6; background: #eff6ff; color: #1d4ed8; border-radius: 7px; padding: 9px 14px; font-size: 13px; font-weight: 500; }
.note-area { width: 100%; border: 1px solid #e2e8f0; border-radius: 7px; padding: 9px 12px; font-size: 12px; resize: none; height: 70px; outline: none; font-family: inherit; }
.toast-bar { background: #f0fdf4; border: 1px solid #86efac; color: #166534; border-radius: 8px; padding: 10px 14px; font-size: 13px; font-weight: 500; margin-top: 18px; display: flex; align-items: center; gap: 8px; }
.toast-dot { background: #22c55e; color: white; border-radius: 50%; width: 18px; height: 18px; display: inline-flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 700; }
.btn-outline { background: white; border: 1px solid #d1d5db; color: #374151; padding: 7px 14px; border-radius: 7px; font-size: 13px; cursor: pointer; font-weight: 500; }
.btn-primary { background: #1d4ed8; color: white; border: none; padding: 7px 14px; border-radius: 7px; font-size: 13px; cursor: pointer; font-weight: 500; }
</style>