# Copyright (c) 2026, Rhocom Technology Ltd and contributors
# For license information, please see license.txt
"""
Salto KS Cloud Access Management provider.

Implements the LockProvider contract for the Salto KS REST API v1.

Provider Code:  salto
Class Path:     rhohotel.integrations.locks.salto_provider.SaltoProvider

Credential storage:
    Credentials are read from the "Salto Settings" singleton DocType.
    The API token (Password field) is NEVER returned to the browser.

Salto KS API overview:
  • Base URL: https://api.saltoks.com (or region-specific endpoint)
  • Authentication: Bearer token — either a long-lived API token or an
    OAuth2 access token obtained via client_credentials flow.
  • All request/response bodies are application/json.
  • Timestamps: ISO 8601 with timezone (e.g. 2026-06-23T14:00:00+00:00).
  • Lock and Key IDs are UUIDs.
  • HTTP 200/201 = success; 4xx/5xx = error.

Key types supported:
  code   — 4–8 digit PIN generated by Salto KS (no hardware needed).
  mobile — Mobile app key delivered to guest via Salto JustIN app.
  card   — RFID card programmed by an online Salto lock or enrollment reader.
"""

from __future__ import annotations

import json
import time as _time
from typing import Any, Optional

from rhohotel.integrations.locks.base import (
    KeyContext,
    LockProvider,
    LockProviderAuthError,
    LockProviderRequestError,
    LockProviderUnavailableError,
    ProviderResult,
)

try:
    from frappe import _
except ImportError:
    def _(s: str, *args, **kwargs) -> str:  # type: ignore[misc]
        return s

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_DEFAULT_BASE = "https://api.saltoks.com"
_TOKEN_EXPIRY_BUFFER = 60   # seconds before expiry to refresh the token
_MAX_KEY_NAME = 100          # Salto KS key name limit


# ---------------------------------------------------------------------------
# Provider class
# ---------------------------------------------------------------------------

class SaltoProvider(LockProvider):
    """
    Salto KS cloud access management lock provider.

    Reads all configuration from the "Salto Settings" singleton DocType.

    connection_config JSON keys (Lock Provider record — non-secret):
        base_url  (str): Override the API base URL.
        site_id   (str): Override the Salto KS site ID from Settings.
        key_type  (str): Override the key type ("code", "mobile", "card").
    """

    def __init__(self, provider_doc: Any) -> None:
        super().__init__(provider_doc)
        config_str = getattr(provider_doc, "connection_config", None) or "{}"
        try:
            self._config: dict = (
                json.loads(config_str) if isinstance(config_str, str) else dict(config_str)
            )
        except (json.JSONDecodeError, TypeError):
            self._config = {}

        # Resolved lazily from Salto Settings + connection_config overrides
        self._base_url: Optional[str] = self._config.get("base_url")
        self._site_id: Optional[str] = self._config.get("site_id")
        self._key_type: Optional[str] = self._config.get("key_type")
        self._settings_loaded: bool = False

        # OAuth2 token cache
        self._token: Optional[str] = None
        self._token_expiry: float = 0.0

    # ------------------------------------------------------------------
    # Settings / credential loading
    # ------------------------------------------------------------------

    def _load_settings(self) -> None:
        """Load Salto Settings from DB (once per provider instance)."""
        if self._settings_loaded:
            return
        import frappe

        doc = frappe.get_cached_doc("Salto Settings")
        if not self._base_url:
            self._base_url = (doc.base_url or _DEFAULT_BASE).rstrip("/")
        else:
            self._base_url = self._base_url.rstrip("/")
        if not self._site_id:
            self._site_id = doc.site_id or ""
        if not self._key_type:
            self._key_type = doc.key_type or "code"
        self._settings_loaded = True

    def _get_credentials(self) -> tuple[str, str]:
        """
        Return (client_id, client_secret) from Salto Settings.

        Raises LockProviderAuthError if not configured.
        Credentials are NEVER logged or returned to the browser.
        """
        import frappe
        from frappe.utils.password import get_decrypted_password

        auth_method = frappe.db.get_single_value("Salto Settings", "auth_method") or "api_token"

        if auth_method == "api_token":
            # Static API token — returned as (token, "")
            api_token = (
                get_decrypted_password("Salto Settings", "Salto Settings", "api_token") or ""
            )
            if not api_token:
                raise LockProviderAuthError(
                    _(
                        "Salto API token is not configured. "
                        "Go to Salto Settings and enter your API Token."
                    )
                )
            return api_token, ""
        else:
            # OAuth2 client credentials
            client_id = frappe.db.get_single_value("Salto Settings", "client_id") or ""
            client_secret = (
                get_decrypted_password("Salto Settings", "Salto Settings", "client_secret") or ""
            )
            if not client_id or not client_secret:
                raise LockProviderAuthError(
                    _(
                        "Salto OAuth2 credentials are not configured. "
                        "Go to Salto Settings and enter your Client ID and Client Secret."
                    )
                )
            return client_id, client_secret

    def _get_access_token(self) -> str:
        """
        Return a valid Bearer token, refreshing if necessary.

        For API Token auth: returns the static token directly.
        For OAuth2: performs the client_credentials flow and caches the token.
        """
        self._load_settings()

        import frappe
        auth_method = frappe.db.get_single_value("Salto Settings", "auth_method") or "api_token"

        if auth_method == "api_token":
            token, _ = self._get_credentials()
            return token

        # OAuth2 — return cached token if still valid
        if self._token and _time.monotonic() < self._token_expiry - _TOKEN_EXPIRY_BUFFER:
            return self._token

        client_id, client_secret = self._get_credentials()
        url = f"{self._base_url}/oauth/token"
        payload = {
            "grant_type": "client_credentials",
            "client_id": client_id,
            "client_secret": client_secret,
        }
        data = self._post_json(url, payload, _skip_auth=True)
        access_token: str = data.get("access_token") or ""
        expires_in = int(data.get("expires_in") or 3600)
        if not access_token:
            raise LockProviderAuthError(
                _("Salto did not return an access_token — check credentials in Salto Settings.")
            )
        self._token = access_token
        self._token_expiry = _time.monotonic() + expires_in
        return self._token

    # ------------------------------------------------------------------
    # HTTP helpers
    # ------------------------------------------------------------------

    def _headers(self) -> dict:
        """Build request headers with Bearer token."""
        return {
            "Authorization": f"Bearer {self._get_access_token()}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    def _post_json(self, url: str, payload: dict, _skip_auth: bool = False) -> dict:
        """POST JSON body, return parsed response dict."""
        try:
            import requests as _req
        except ImportError as exc:
            raise LockProviderUnavailableError("requests library not available") from exc

        headers = (
            {"Content-Type": "application/json", "Accept": "application/json"}
            if _skip_auth
            else self._headers()
        )
        try:
            resp = _req.post(url, json=payload, headers=headers, timeout=self.timeout)
        except _req.exceptions.Timeout as exc:
            raise LockProviderUnavailableError(
                _("Salto API timed out ({0}s).").format(self.timeout)
            ) from exc
        except _req.exceptions.ConnectionError as exc:
            raise LockProviderUnavailableError(
                _("Cannot reach Salto API: {0}").format(str(exc))
            ) from exc

        return self._parse(resp)

    def _patch_json(self, url: str, payload: dict) -> dict:
        """PATCH JSON body, return parsed response dict."""
        try:
            import requests as _req
        except ImportError as exc:
            raise LockProviderUnavailableError("requests library not available") from exc

        try:
            resp = _req.patch(url, json=payload, headers=self._headers(), timeout=self.timeout)
        except _req.exceptions.Timeout as exc:
            raise LockProviderUnavailableError(
                _("Salto API timed out ({0}s).").format(self.timeout)
            ) from exc
        except _req.exceptions.ConnectionError as exc:
            raise LockProviderUnavailableError(
                _("Cannot reach Salto API: {0}").format(str(exc))
            ) from exc

        return self._parse(resp)

    def _delete(self, url: str) -> dict:
        """DELETE request, return parsed response dict (or empty dict on 204)."""
        try:
            import requests as _req
        except ImportError as exc:
            raise LockProviderUnavailableError("requests library not available") from exc

        try:
            resp = _req.delete(url, headers=self._headers(), timeout=self.timeout)
        except _req.exceptions.Timeout as exc:
            raise LockProviderUnavailableError(
                _("Salto API timed out ({0}s).").format(self.timeout)
            ) from exc
        except _req.exceptions.ConnectionError as exc:
            raise LockProviderUnavailableError(
                _("Cannot reach Salto API: {0}").format(str(exc))
            ) from exc

        if resp.status_code == 204:
            return {}
        return self._parse(resp)

    def _get(self, url: str, params: Optional[dict] = None) -> dict:
        """GET request, return parsed response dict."""
        try:
            import requests as _req
        except ImportError as exc:
            raise LockProviderUnavailableError("requests library not available") from exc

        try:
            resp = _req.get(url, params=params or {}, headers=self._headers(), timeout=self.timeout)
        except _req.exceptions.Timeout as exc:
            raise LockProviderUnavailableError(
                _("Salto API timed out ({0}s).").format(self.timeout)
            ) from exc
        except _req.exceptions.ConnectionError as exc:
            raise LockProviderUnavailableError(
                _("Cannot reach Salto API: {0}").format(str(exc))
            ) from exc

        return self._parse(resp)

    def _parse(self, resp: Any) -> dict:
        """Parse HTTP response and raise on errors."""
        _NOT_FOUND = {404}
        _AUTH_ERRORS = {401, 403}

        if resp.status_code in _AUTH_ERRORS:
            raise LockProviderAuthError(
                _("Salto API authentication failed (HTTP {0}). Check API token/credentials.").format(
                    resp.status_code
                )
            )

        if resp.status_code == 404:
            raise LockProviderRequestError(
                _("Salto resource not found (HTTP 404). Check lock/key IDs.")
            )

        if resp.status_code >= 400:
            try:
                err_data = resp.json()
            except ValueError:
                err_data = {}
            message = (
                err_data.get("message")
                or err_data.get("error")
                or err_data.get("detail")
                or f"HTTP {resp.status_code}"
            )
            if isinstance(message, list):
                message = "; ".join(str(m) for m in message)
            raise LockProviderRequestError(
                _("Salto API error: {0}").format(message)
            )

        if resp.status_code == 204:
            return {}

        try:
            return resp.json()
        except ValueError as exc:
            raise LockProviderUnavailableError(
                _("Salto API returned non-JSON response.")
            ) from exc

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _site_url(self) -> str:
        """Return the base URL prefix for site-scoped endpoints."""
        self._load_settings()
        if self._site_id:
            return f"{self._base_url}/api/v1/sites/{self._site_id}"
        return f"{self._base_url}/api/v1"

    def _key_name(self, context: KeyContext) -> str:
        """Build the key name shown in the Salto dashboard."""
        import frappe
        prefix = frappe.db.get_single_value("Salto Settings", "key_name_prefix") or "Guest"
        raw = f"{prefix} {context.guest_name}"
        return raw[:_MAX_KEY_NAME]

    @staticmethod
    def _iso(dt_str: str) -> str:
        """
        Convert a Frappe datetime string to an ISO 8601 string with UTC offset.

        Frappe stores datetimes as 'YYYY-MM-DD HH:MM:SS'; Salto expects
        'YYYY-MM-DDTHH:MM:SS+00:00'.
        """
        s = str(dt_str).strip()
        # Already has T separator / timezone info — return as-is
        if "T" in s and ("+" in s[10:] or "Z" in s):
            return s
        # Convert space separator to T and append UTC indicator
        s = s.replace(" ", "T")
        if not s.endswith("Z") and "+" not in s[10:]:
            s = s + "+00:00"
        return s

    # ------------------------------------------------------------------
    # LockProvider implementation
    # ------------------------------------------------------------------

    def issue_key(self, context: KeyContext) -> ProviderResult:
        """
        Create a new Salto KS key for the guest.

        key_type = code   → PIN code returned in ProviderResult.provider_data["code"]
        key_type = mobile → Mobile key sent to guest app (guest_email required in context.extra)
        key_type = card   → RFID card programmed when tapped on Salto online reader
        """
        self._load_settings()
        url = f"{self._site_url()}/keys"
        payload: dict = {
            "name": self._key_name(context),
            "starts_at": self._iso(context.valid_from),
            "expires_at": self._iso(context.valid_until),
            "locks": [context.external_lock_id],
            "key_type": self._key_type or "code",
        }

        if self._key_type == "mobile":
            guest_email = str(context.extra.get("guest_email") or "").strip()
            if not guest_email:
                raise LockProviderRequestError(
                    _(
                        "Mobile key issuance requires the guest's email address. "
                        "Set guest_email in context.extra or configure guest email in the reservation."
                    )
                )
            payload["email"] = guest_email

        raw = self._post_json(url, payload)
        key_id = str(raw.get("id") or "")
        if not key_id:
            return ProviderResult(
                success=False,
                raw_response=self._redact(raw),
                error=_("Salto did not return a key ID."),
            )

        provider_data: dict = {
            "key_type": self._key_type or "code",
            "key_id": key_id,
        }
        # For PIN code keys, surface the code to the PMS so staff can give it to the guest
        if raw.get("code"):
            provider_data["code"] = str(raw["code"])

        return ProviderResult(
            success=True,
            external_key_id=key_id,
            provider_request_id=str(raw.get("request_id") or raw.get("id") or ""),
            raw_response=self._redact(raw),
            provider_data=provider_data,
        )

    def reissue_key(self, context: KeyContext, existing_key_id: str) -> ProviderResult:
        """Delete the existing key then issue a fresh one."""
        cancel = self._delete_key(existing_key_id)
        if not cancel.success:
            return cancel
        return self.issue_key(context)

    def update_key_validity(self, context: KeyContext, existing_key_id: str) -> ProviderResult:
        """
        Update the valid_until time of an existing key without reissuing it.

        Uses PATCH /keys/{key_id} to change starts_at / expires_at.
        """
        self._load_settings()
        url = f"{self._site_url()}/keys/{existing_key_id}"
        payload = {
            "starts_at": self._iso(context.valid_from),
            "expires_at": self._iso(context.valid_until),
        }
        raw = self._patch_json(url, payload)
        return ProviderResult(
            success=True,
            external_key_id=existing_key_id,
            raw_response=self._redact(raw),
            provider_data={"updated": True},
        )

    def cancel_key(
        self,
        key_id: str,
        room_mapping: Any,
        context: Optional[KeyContext] = None,
    ) -> ProviderResult:
        """Delete a key from Salto KS."""
        return self._delete_key(key_id)

    def _delete_key(self, key_id: str) -> ProviderResult:
        """DELETE /keys/{key_id}. Treats 404 as already-cancelled (idempotent)."""
        self._load_settings()
        url = f"{self._site_url()}/keys/{key_id}"
        try:
            self._delete(url)
        except LockProviderRequestError as exc:
            if "404" in str(exc):
                # Key already gone — treat as success
                return ProviderResult(
                    success=True,
                    external_key_id=key_id,
                    provider_data={"already_cancelled": True},
                )
            raise
        return ProviderResult(
            success=True,
            external_key_id=key_id,
            provider_data={"cancelled": True},
        )

    def transfer_key(
        self,
        context: KeyContext,
        old_room_mapping: Any,
        new_room_mapping: Any,
        existing_key_id: str,
    ) -> ProviderResult:
        """Cancel the old-room key and issue a new key for the new room."""
        cancel = self._delete_key(existing_key_id)
        if not cancel.success:
            return cancel
        return self.issue_key(context)

    def get_lock_status(self, room_mapping: Any) -> ProviderResult:
        """
        Query the current status of a Salto lock (battery, connectivity, locked state).
        """
        self._load_settings()
        lock_id = getattr(room_mapping, "external_lock_id", None) or (
            room_mapping.get("external_lock_id") if isinstance(room_mapping, dict) else None
        )
        if not lock_id:
            return ProviderResult(
                success=False,
                error=_("Room Lock Mapping has no external_lock_id."),
            )

        url = f"{self._site_url()}/locks/{lock_id}"
        try:
            raw = self._get(url)
        except LockProviderRequestError as exc:
            return ProviderResult(success=False, error=str(exc))

        # Normalise nested Salto response into a flat provider_data dict
        connectivity = raw.get("connectivity") or {}
        battery = raw.get("battery") or {}
        lock_state = raw.get("lock_state") or {}

        provider_data = {
            "status": connectivity.get("status") or raw.get("status") or "unknown",
            "battery_level": battery.get("level") if battery else raw.get("battery_level"),
            "is_locked": lock_state.get("state") == "locked" if lock_state else None,
            "lock_id": lock_id,
        }

        return ProviderResult(
            success=True,
            raw_response=self._redact(raw),
            provider_data=provider_data,
        )

    def health_check(self) -> ProviderResult:
        """
        Validate Salto KS connectivity and credentials.

        Fetches /sites (or /locks if no site_id) to confirm the token works.
        """
        self._load_settings()
        try:
            if self._site_id:
                url = f"{self._site_url()}/locks"
                self._get(url, params={"limit": 1})
            else:
                url = f"{self._base_url}/api/v1/sites"
                self._get(url, params={"limit": 1})
        except LockProviderAuthError:
            raise
        except LockProviderUnavailableError:
            raise
        except LockProviderRequestError as exc:
            # A 404 on /locks still means auth succeeded
            if "404" not in str(exc):
                raise

        return ProviderResult(
            success=True,
            provider_data={"message": "Salto KS API reachable and credentials valid."},
        )
